spring:
  datasource:
    username: test
    password: test
    url: jdbc:mysql://localhost:3306/chat_system?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver